#!/usr/bin/env bash
USAGE="usage: $0 [-h] FILE_NAME [RUN_TYPE]"
RUN_TYPE="bash"

# Colorful logging.
echogood() { echo "[1;32m *[0m $@"; }
echowarn() { echo "[1;33m *[0m $@"; }
echobad()  { echo "[1;31m *[0m $@"; }

# Echo an optional error message, then show expected usage and
# exit an error status code.
errorout() {
  [ -n "$1" ] && echobad "$@"
  echo "$USAGE"
  exit 1
}

# Echo the expected usage along with a detailed help message.
printhelp() {
  cat <<EOF
$USAGE

Create an executable with an appropriate shebang. Will immediately begin
editing with \$VISUAL or \$EDITOR if either are set.

If FILE_NAME already exists, we'll immediately start editing it with
your preferred editor (without otherwise modifying the file in any way).

positional arguments:
 FILE_NAME    path to the new script
 RUN_TYPE     type to put in the shebang (default: $RUN_TYPE)

optional arguments:
 -h           show this help message and exit

current environment (if you're curious):
 \$VISUAL:     \`$VISUAL'
 \$EDITOR:     \`$EDITOR'
EOF
}

# Parse any arguments. Put a colon after any options that expect
# $OPTARGs to follow. The colon at the start is unrelated.
while getopts ":h" opt; do
  case "$opt" in
    h)
      # Just print the help message and exit happily.
      printhelp
      exit 0
      ;;

    # Additional options go here.

    ?)
      # Don't tolerate unrecognized options.
      errorout "unrecognized option: \`-$OPTARG'"
      ;;
  esac
done

shift $((OPTIND - 1))

if [ -z "$1" ]; then
  errorout "expected at least one argument"
fi

filename="$1"
runtype="${2:-$RUN_TYPE}"

if ! [ -e "$filename" ]; then
  if [ "${runtype:0:1}" = "/" ]; then
    if [ -e "$runtype" ]; then
      echo "#!$runtype" > "$filename"

    else
      errorout "Absolute path does not exist: $runtype"
    fi

  else
    case "$runtype" in
      "bash")
        cat <<- EOSF > "$filename"
	#!/usr/bin/env $runtype
	USAGE="usage: \$0 [-h] OTHER_ARGS_ETC"

	# Colorful logging.
	echogood() { echo "[1;32m *[0m \$@"; }
	echowarn() { echo "[1;33m *[0m \$@"; }
	echobad()  { echo "[1;31m *[0m \$@"; }

	# Echo an optional error message, then show expected usage and
	# exit an error status code.
	errorout() {
	  [ -n "\$1" ] && echobad "\$@"
	  echo "\$USAGE"
	  exit 1
	}

	# Echo the expected usage along with a detailed help message.
	printhelp() {
	  cat <<EOF
	\$USAGE

	Description of whatever this does.

	positional arguments:
	 ARG_NAME     what's this argument about
	 ANOTHER_ARG  maybe this one's optional (default: \$ANOTHER_ARG)

	optional arguments:
	 -h           show this help message and exit
	EOF
	}

	# Parse any arguments. Put a colon after any options that expect
	# \$OPTARGs to follow. The colon at the start is unrelated.
	while getopts ":h" opt; do
	  case "\$opt" in
	    h)
	      # Just print the help message and exit happily.
	      printhelp
	      exit 0
	      ;;

	    # Additional options go here.

	    ?)
	      # Don't tolerate unrecognized options.
	      errorout "unrecognized option: \\\`-\$OPTARG'"
	      ;;
	  esac
	done

	shift \$((OPTIND - 1))

	# Your code begins here.
	EOSF
        ;;

      "python3")
        cat <<- EOSF > "$filename"
	#!/usr/bin/env $runtype
	from argparse           import  ArgumentParser

	DETAILED_DESCRIPTION = """\\
	This will show up on the help screen."""

	# Your classes and functions go here.

	# Prep the argument parser.
	parser  = ArgumentParser(description = DETAILED_DESCRIPTION)

	# The two arguments here are just examples to remind you how to
	# use argparse.
	parser.add_argument("integers",
	                    metavar = "N",
	                    type    = int,
	                    nargs   = "+",
	                    help    = "any number of integers")
	parser.add_argument("-s", "--sum",
	                    dest    = "accumulate",
	                    action  = "store_const",
	                    const   = sum,
	                    default = max,
	                    help    = "sum the integers (default: max)")

	# Parse the actual arguments.
	args    = parser.parse_args()

	# Replace this with your own code. As are the arguments above,
	# this exists only to serve as an example.
	print(args.accumulate(args.integers))
	EOSF
        ;;

      *)
        echo "#!/usr/bin/env $runtype" > "$filename"
        ;;
    esac
  fi

  chmod +x "$filename"
fi

if [ -n "$VISUAL" -a -e "$VISUAL" ]; then
  exec "$VISUAL" "$filename"

elif [ -n "$EDITOR" -a -e "$EDITOR" ]; then
  exec "$EDITOR" "$filename"

else
  echo "Created $filename (or it already exists)"
  echo "Couldn't find \$VISUAL or \$EDITOR"
fi
